# Generated by Django 4.2 on 2026-02-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('debug_count', models.IntegerField(default=0)),
                ('auth_count', models.IntegerField(default=0)),
                ('api_count', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'logs_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('debug', 'Debug')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('auth', 'Authentification'), ('user', 'Utilisateur'), ('system', 'Système'), ('data', 'Données'), ('api', 'API'), ('security', 'Sécurité')], default='system', max_length=20),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user'], name='logs_log_user_id_e2a55a_idx'),
        ),
    ]
