# Generated by Django 4.2.28 on 2026-02-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'administrateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BanqueExercices',
            fields=[
                ('id_exercice', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('niveau_difficulte', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')])),
                ('fichier_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banque_exercices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_class', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'classe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('date_inscription', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'etudiant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_matière', models.CharField(max_length=100)),
                ('coefficient', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'matiere',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('type_evaluation', models.CharField(choices=[('devoir', 'Devoir'), ('examen', 'Examen'), ('tp', 'Travaux Pratiques')], max_length=10)),
                ('valeur_note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_note', models.DateField()),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_professeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=100)),
                ('prenom_prof', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'professeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id_ressource', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('Type_ressource', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('lien', 'Lien web'), ('document', 'Document')], max_length=10)),
                ('fichier_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ressource',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
