# Generated by Django 4.2 on 2026-02-23 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_class', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, db_column='classe_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classe')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_matiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_matière', models.CharField(max_length=100)),
                ('coefficient', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'matiere',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_professeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=100)),
                ('prenom_prof', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'professeur',
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id_ressource', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('Type_ressource', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('lien', 'Lien'), ('document', 'Document')], max_length=20)),
                ('fichier_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par_admin', models.ForeignKey(db_column='cree_par_admin', on_delete=django.db.models.deletion.CASCADE, to='academic.administrateur')),
                ('matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, to='academic.matiere')),
            ],
            options={
                'db_table': 'ressource',
            },
        ),
        migrations.CreateModel(
            name='BanqueExercices',
            fields=[
                ('id_exercice', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('niveau_difficulte', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')])),
                ('fichier_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(db_column='cree_par', on_delete=django.db.models.deletion.CASCADE, to='academic.professeur')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='academic.matiere')),
            ],
            options={
                'db_table': 'banque_exercices',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('type_evaluation', models.CharField(choices=[('devoir', 'Devoir'), ('examen', 'Examen'), ('tp', 'Travaux Pratiques')], max_length=20)),
                ('valeur_note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_note', models.DateField()),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to='academic.administrateur')),
                ('matiere', models.ForeignKey(db_column='id_matiere', on_delete=django.db.models.deletion.CASCADE, to='academic.matiere')),
                ('student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
            ],
            options={
                'db_table': 'note',
                'unique_together': {('student', 'matiere', 'type_evaluation', 'date_note')},
            },
        ),
    ]
