# Generated by Django 4.2 on 2026-02-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('cours', 'Cours'), ('examen', 'Examen'), ('tp', 'TP'), ('reunion', 'Réunion'), ('devoir', 'Devoir'), ('autre', 'Autre')], default='cours', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'date'], name='events_even_user_id_73ae47_idx'),
        ),
    ]
