# Generated by Django 4.2.28 on 2026-02-22 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fichier_modele', models.FileField(blank=True, null=True, upload_to='modeles_ia/')),
                ('precision', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modèle IA',
                'verbose_name_plural': 'Modèles IA',
                'db_table': 'modele_ia',
            },
        ),
        migrations.CreateModel(
            name='SuggestionExercice',
            fields=[
                ('id_suggestion', models.AutoField(primary_key=True, serialize=False)),
                ('note_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('raison', models.TextField()),
                ('niveau_suggere', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')])),
                ('date_suggestion', models.DateTimeField(auto_now_add=True)),
                ('est_consultee', models.BooleanField(default=False)),
                ('est_faite', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='academic.etudiant')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.banqueexercices')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.matiere')),
            ],
            options={
                'db_table': 'suggestion_exercice',
                'ordering': ['-date_suggestion'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueApprentissage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('exercices_realises', models.IntegerField(default=0)),
                ('exercices_reussis', models.IntegerField(default=0)),
                ('taux_reussite', models.FloatField(default=0.0)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.matiere')),
            ],
            options={
                'db_table': 'statistique_apprentissage',
                'unique_together': {('etudiant', 'matiere')},
            },
        ),
    ]
