# Generated by Django 4.2 on 2026-02-23 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('progression', models.FloatField(default=0)),
                ('nb_exercices', models.IntegerField(default=0)),
                ('taux_reussite', models.FloatField(default=0)),
                ('temps_moyen', models.IntegerField(default=0)),
                ('date_calcul', models.DateField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.matiere')),
            ],
            options={
                'db_table': 'stats_performance',
                'unique_together': {('etudiant', 'matiere', 'date_calcul')},
            },
        ),
    ]
