# Generated by Django 4.2 on 2026-02-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('taux_reussite', models.FloatField(default=0)),
                ('nb_etudiants', models.IntegerField(default=0)),
                ('nb_notes', models.IntegerField(default=0)),
                ('meilleure_matiere', models.CharField(blank=True, max_length=100)),
                ('matiere_faible', models.CharField(blank=True, max_length=100)),
                ('distribution', models.JSONField(default=dict)),
                ('date_calcul', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stats_classe',
            },
        ),
        migrations.CreateModel(
            name='GlobalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_etudiants', models.IntegerField(default=0)),
                ('total_professeurs', models.IntegerField(default=0)),
                ('total_classes', models.IntegerField(default=0)),
                ('total_matieres', models.IntegerField(default=0)),
                ('total_notes', models.IntegerField(default=0)),
                ('moyenne_generale', models.FloatField(blank=True, null=True)),
                ('taux_reussite_global', models.FloatField(default=0)),
                ('utilisateurs_actifs', models.IntegerField(default=0)),
                ('connexions_jour', models.IntegerField(default=0)),
                ('date_calcul', models.DateField(auto_now_add=True, unique=True)),
            ],
            options={
                'db_table': 'stats_global',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.AddField(
            model_name='performancestat',
            name='nb_notes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancestat',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_stats', to='academic.etudiant'),
        ),
        migrations.AddIndex(
            model_name='performancestat',
            index=models.Index(fields=['etudiant', 'date_calcul'], name='stats_perfo_etudian_56eb98_idx'),
        ),
        migrations.AddField(
            model_name='classestat',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='academic.classe'),
        ),
        migrations.AlterUniqueTogether(
            name='classestat',
            unique_together={('classe', 'date_calcul')},
        ),
    ]
